In [35]:
import numpy as np

co = np.array([[1,2,3],[4,5,6],[7,8,9]])
re = np.array([[1,2,3],[4,5,6],[7,8,9]])
type((co.T * re.T))
np.reshape(co,(1,9)).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [74]:
a = np.random.randint(1,100,size=[10,3])
print(a)
# 取出0，3行的数据
a[[0,3]]
# 取出第一列的数据
a[:,0:1]
# 取出第0,2列的数据
a[:,[0,2]]
# 取出第1行,2列的数据
a[1,2]

[[36 37  4]
 [92 98 41]
 [ 6 90 64]
 [17  6 99]
 [96 71 12]
 [13 22 84]
 [30 52 48]
 [32  9 66]
 [92 75 17]
 [82 61 70]]


41

In [87]:
# 范围0-1
b = np.random.random((2,3))
# 范围2-300
c = np.random.randint(2,300,size=(2,3))
c

array([[110,  46, 199],
       [ 96, 150, 117]])

In [97]:
jjj = np.array([[1,2,3],[4,5,6],[7,8,9]])
# -1可以自动计算行或列
jjj.reshape(-1,3)
jjj.reshape(3,-1)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
oo = np.zeros([3,3])
oo


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [110]:
a = [1,2,3,4,5,6,7,8,9]
np.diag(a)
np.diag(np.diag(a))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a = np.identity(3)
b = np.array([1,0,0,0,1,0,0,0,1])
np.allclose(a,b.reshape(3,-1))

True

In [144]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]]).T
# np.dot(a,b)
# a*b
np.multiply(a,b)


array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [152]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.mat([[1,2,3],[4,5,6],[7,8,9]])
np.dot(a,b)
a*b

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [194]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[2],[3]]).T
c = np.array([[1,34,5]]).T
# np.dot(a,b)
c
np.dot(a,c)

array([[ 84],
       [204]])

In [200]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
a**3
np.power(a,3)

matrix([[  1,   8,  27],
        [ 64, 125, 216],
        [343, 512, 729]], dtype=int32)

In [214]:
A = np.array([[1, 2], [3, 4]])
n = 2

# 矩阵的乘方
A_n = np.linalg.matrix_power(A, n)
np.mat(A)**n
print("矩阵的乘方 A^2:\n", A_n)
np.mat(A)**n


A**2
np.power(A,2)

矩阵的乘方 A^2:
 [[ 7 10]
 [15 22]]


array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [1]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.I

NameError: name 'np' is not defined

In [21]:

import numpy as np

n = 3  # 矩阵尺寸

# 生成随机矩阵

matrix = np.random.rand(n, n)

# 生成对称矩阵

a = (matrix + matrix.T) / 2
type(a == a.T)
a == a.T

# 生成逆矩阵
np.mat(a).I


matrix([[ 3.20249407,  1.1192169 , -4.65888391],
        [ 1.1192169 ,  3.5711417 , -4.50415283],
        [-4.65888391, -4.50415283, 11.74740878]])

In [49]:
a = np.array([
    [1, -4, 0, 2],
    [-1, 2, -1,-1],
    [1, -2, 3, 5],
    [2, -6, 1 ,3]
])
b = np.zeros((3,3))
a
np.dot(np.linalg.inv(a),a.T)


LinAlgError: Singular matrix

In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a
np.linalg.det(a)

-9.51619735392994e-16

In [63]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# 将向量作为矩阵的列
matrix = np.column_stack((v1, v2, v3))
matrix
det = np.linalg.det(matrix)
det
rank = np.linalg.matrix_rank(matrix)
matrix.shape[1]

3

In [70]:
import numpy as np

# 定义一个矩阵
matrix = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 2, 1]
])

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

print("矩阵：")
print(matrix)
print("\n矩阵的秩：", rank)

矩阵：
[[1 2 3]
 [2 4 6]
 [3 2 1]]

矩阵的秩： 2


In [79]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.dot(a.T,b)
np.linalg.norm(b)

8.774964387392123

In [91]:
import numpy as np

a = np.array([1, 1, 1])
b = np.array([2, -4, 2])
d = np.array([-1, 0, 1])

c = np.cross(a, b)


np.dot(b.T, c)

0

In [96]:
import numpy as np

# 定义旋转角度 (以弧度为单位)
theta = np.pi / 4  # 45度

# 生成二维旋转矩阵
Q = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# 计算 Q 的转置
Q_T = Q.T

# 计算 Q^T Q
result = np.dot(Q_T, Q)

print("Q:")
print(Q)
print("\nQ^T:")
print(Q_T)
print("\nQ^T Q:")
print(result)

Q:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Q^T:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Q^T Q:
[[ 1.00000000e+00 -4.26642159e-17]
 [-4.26642159e-17  1.00000000e+00]]


In [111]:
S = np.array([[8.5,9],[4.5,4],[33,1]]) #行商店 列水果的 价格
H = np.array([[8,3,4],[3,4,5]]) #行水果列人员 购买数
T = np.array([[1000,2000],[2000,3000]])#行人员 列城镇 购买数
# 每个人在各个商店消费金额
np.dot(H,S)
# 每个城镇购买数量
np.dot(T,S)

array([[26500., 44000.],
       [12500., 21000.],
       [35000., 69000.]])