In [35]:
import numpy as np

co = np.array([[1,2,3],[4,5,6],[7,8,9]])
re = np.array([[1,2,3],[4,5,6],[7,8,9]])
type((co.T * re.T))
np.reshape(co,(1,9)).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [74]:
a = np.random.randint(1,100,size=[10,3])
print(a)
# 取出0，3行的数据
a[[0,3]]
# 取出第一列的数据
a[:,0:1]
# 取出第0,2列的数据
a[:,[0,2]]
# 取出第1行,2列的数据
a[1,2]

[[36 37  4]
 [92 98 41]
 [ 6 90 64]
 [17  6 99]
 [96 71 12]
 [13 22 84]
 [30 52 48]
 [32  9 66]
 [92 75 17]
 [82 61 70]]


41

In [87]:
# 范围0-1
b = np.random.random((2,3))
# 范围2-300
c = np.random.randint(2,300,size=(2,3))
c

array([[110,  46, 199],
       [ 96, 150, 117]])

In [97]:
jjj = np.array([[1,2,3],[4,5,6],[7,8,9]])
# -1可以自动计算行或列
jjj.reshape(-1,3)
jjj.reshape(3,-1)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
oo = np.zeros([3,3])
oo


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [110]:
a = [1,2,3,4,5,6,7,8,9]
np.diag(a)
np.diag(np.diag(a))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a = np.identity(3)
b = np.array([1,0,0,0,1,0,0,0,1])
np.allclose(a,b.reshape(3,-1))

True

In [144]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]]).T
# np.dot(a,b)
# a*b
np.multiply(a,b)


array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [152]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.mat([[1,2,3],[4,5,6],[7,8,9]])
np.dot(a,b)
a*b

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [194]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[2],[3]]).T
c = np.array([[1,34,5]]).T
# np.dot(a,b)
c
np.dot(a,c)

array([[ 84],
       [204]])

In [200]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
a**3
np.power(a,3)

matrix([[  1,   8,  27],
        [ 64, 125, 216],
        [343, 512, 729]], dtype=int32)

In [214]:
A = np.array([[1, 2], [3, 4]])
n = 2

# 矩阵的乘方
A_n = np.linalg.matrix_power(A, n)
np.mat(A)**n
print("矩阵的乘方 A^2:\n", A_n)
np.mat(A)**n


A**2
np.power(A,2)

矩阵的乘方 A^2:
 [[ 7 10]
 [15 22]]


array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [216]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'