In [12]:
import numpy as np
np1 = np.arange(100,150,2)
random_array = np.random.randint(0,100,(3, 3))
print(random_array)

[[90  6 84]
 [72 94 27]
 [62 88 14]]


In [15]:
random_array

array([[90,  6, 84],
       [72, 94, 27],
       [62, 88, 14]])

In [25]:
new = np.concatenate((random_array,random_array,random_array), axis=1)
print(new)

[[90  6 84 90  6 84 90  6 84]
 [72 94 27 72 94 27 72 94 27]
 [62 88 14 62 88 14 62 88 14]]


In [44]:
print(np.transpose(new))
print(new.T.mean(axis=0))

[[90 72 62]
 [ 6 94 88]
 [84 27 14]
 [90 72 62]
 [ 6 94 88]
 [84 27 14]
 [90 72 62]
 [ 6 94 88]
 [84 27 14]]
[60.         64.33333333 54.66666667]


In [48]:
str_np = np.array([["13","你妈的","1的"],["阀门","s是否","啊是否能"]])

In [50]:
str_np

array([['13', '你妈的', '1的'],
       ['阀门', 's是否', '啊是否能']], dtype='<U4')

In [13]:
import numpy as np

print ('连接两个字符串：')
print (np.char.add(['hello'],[' xyz']))
print ('\n')

print ('连接示例：')
print (np.char.add(['hello', 'hi'],[' abc', ' xyz']))


print (np.char.center('Runoob', 13,fillchar = '3'))

print (np.char.capitalize('runoob'))

连接两个字符串：
['hello xyz']


连接示例：
['hello abc' 'hi xyz']
3333Runoob333
Runoob


In [18]:
print (np.char.lower(['RUNOOB','GOOGLE']))

['runoob' 'google']


In [22]:
print (np.char.split ('www.runoob.com', sep = 'w'))

['', '', '', '.runoob.com']


In [25]:
import numpy as np

a = np.array([0,30,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度
print (np.sin(a*np.pi/180))
print ('\n')
print ('数组中角度的余弦值：')
print (np.cos(a*np.pi/180))
print ('\n')
print ('数组中角度的正切值：')
print (np.tan(a*np.pi/180))

print(np.sin(60))

不同角度的正弦值：
[0.         0.5        0.70710678 0.8660254  1.        ]


数组中角度的余弦值：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


数组中角度的正切值：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
-0.3048106211022167


In [28]:
import numpy as np

a = np.array([0,30,45,60,90])
print ('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)
print (sin)
print ('\n')
print ('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)
print (inv)
print ('\n')
print ('通过转化为角度制来检查结果：')
print (np.degrees(inv))
print ('\n')
print ('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)
print (cos)
print ('\n')
print ('反余弦：')
inv = np.arccos(cos)
print (inv)
print ('\n')
print ('角度制单位：')
print (np.degrees(inv))
print ('\n')
print ('tan 函数：')
tan = np.tan(a*np.pi/180)
print (tan)
print ('\n')
print ('反正切：')
inv = np.arctan(tan)
print (inv)
print ('\n')
print ('角度制单位：')
print (np.degrees(inv))

含有正弦值的数组：
[0.         0.5        0.70710678 0.8660254  1.        ]


计算角度的反正弦，返回值以弧度为单位：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


通过转化为角度制来检查结果：
[ 0. 30. 45. 60. 90.]


arccos 和 arctan 函数行为类似：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


反余弦：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


角度制单位：
[ 0. 30. 45. 60. 90.]


tan 函数：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


反正切：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


角度制单位：
[ 0. 30. 45. 60. 90.]


In [29]:
import numpy as np

a = np.array([1.0,5.55,  123,  0.567,  25.532])
print  ('原数组：')
print (a)
print ('\n')
print ('舍入后：')
print (np.around(a))
print (np.around(a, decimals =  1))
print (np.around(a, decimals =  -1))

原数组：
[  1.      5.55  123.      0.567  25.532]


舍入后：
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
